### ISSUE TITLE
icon and text is not in line 

### ISSUE THREAD

**Issue by rhgiter** [marcokreeft87/room-card#1]
Thanks - great card

is it possible to get the icon and text at the same line 
![image](https://user-images.githubusercontent.com/61065752/161327861-423abb53-99fb-4917-806f-c916733f0a0e.png)

**Comment by marcokreeft87** [comment]
Good one! I will look into it

**Comment by marcokreeft87** [comment]
Try the latest version

**Comment by rhgiter** [comment]
That was quick :-)   but I still have this version

![image](https://user-images.githubusercontent.com/61065752/161331297-e142e0d2-caf0-4911-913b-3ac8ee61d5de.png)

**Comment by marcokreeft87** [comment]
Forgot to up the version. Been a while haha

**Comment by rhgiter** [comment]
ha ha   :-) 

I'm on 0.0.3 - but I see no different

**Comment by marcokreeft87** [comment]
> ha ha :-)
> 
> I'm on 0.0.3 - but I see no different

Yeah not working for me either. Hoped it was an issue on my end. Ok, back to the drawing board

**Comment by marcokreeft87** [comment]
I will check it on Monday.

**Comment by marcokreeft87** [comment]
@rhgiter I was bothering me, so I fixed it in v0.0.4. Can you try it?

**Comment by rhgiter** [comment]
![image](https://user-images.githubusercontent.com/61065752/161378325-1362686e-c431-4c8e-84ab-0c2927782af6.png)

**Comment by marcokreeft87** [comment]
Yeah some icons are different.

**Comment by theOrakle** [comment]
Just FYI - I had to add style to align the info entities...

<img width="382" alt="image" src="https://user-images.githubusercontent.com/37029980/184346643-1c6a23ca-5369-4e94-bc98-2f526d7f3fbf.png">

With the following code:
```
type: custom:room-card
title: Foyer
entity: light.f_entry
tap_action:
  action: toggle
icon: true
style: |
  div.entities-info-row {
    padding-right: 0px;
    top: 10px;
  }
  div.state.entity {
    margin-right: 0px;
  }
info_entities:
- entity: binary_sensor.f_motion
  show_icon: true    
...
```

**Comment by marcokreeft87** [comment]
> Just FYI - I had to add style to align the info entities...
> 
> <img alt="image" width="382" src="https://user-images.githubusercontent.com/37029980/184346643-1c6a23ca-5369-4e94-bc98-2f526d7f3fbf.png">
> 
> With the following code:
> 
> ```
> type: custom:room-card
> title: Foyer
> entity: light.f_entry
> tap_action:
>   action: toggle
> icon: true
> style: |
>   div.entities-info-row {
>     padding-right: 0px;
>     top: 10px;
>   }
>   div.state.entity {
>     margin-right: 0px;
>   }
> info_entities:
> - entity: binary_sensor.f_motion
>   show_icon: true    
> ...
> ```

Thats will work for just icons, yes, but not for sensors with text base values like temp or lux
![image](https://user-images.githubusercontent.com/10223677/184347389-5724f606-9924-4579-a505-8fd611920f9b.png)

**Comment by marcokreeft87** [comment]
@theOrakle Check newest version

**Comment by rhgiter** [comment]
hi
great thanks

some are ok and some aint

maybe it is an icon problem?

[image: image.png]

/René.


Den lør. 2. apr. 2022 kl. 10.10 skrev Marco Kreeft ***@***.***
