### ISSUE TITLE
Trying to Change Icon Color for One Entity

### ISSUE THREAD

**Issue by pkscout** [marcokreeft87/room-card#11]
I'm trying to change the icon color on one entity in the entities list.  The documentation implies that I can apply a style to a given entity, but I can't figure out what CSS will do that.

**Comment by marcokreeft87** [comment]
For example:

`entities:
  - entity: light.mancave_lamp
    name: Plafond
    tap_action:
      action: toggle
    styles:
      color: red`

**Comment by pkscout** [comment]
Unfortunately that didn't work, even after updating the mod from HACS. The indenting didn't seem to come across on your reply, but I tried a few different combos without luck. I can ask in the HA forum thread if it would be better to do it there.

**Comment by marcokreeft87** [comment]
Ah sorry, I've read you question too fast. Icon color is not possible atm. Maybe in the future. You could try card mod maybe?
