### ISSUE TITLE
Title overlaps info entities

### ISSUE THREAD

**Issue by Holger-H** [marcokreeft87/room-card#113]
**Which version of Room Card?**
- latest

**Describe the bug**
Use Room Card in a horizontal stack to limit the horizontal size.
In case of card is to small the title overlaps the area for the info entities.

![image](https://user-images.githubusercontent.com/82891537/201485087-93fa902d-31dd-403d-9c44-aabbfc41a1f0.png)

**Expected behavior**
Title should not overlap the info entities area.
It would be awesome to add a linebreak before the title. 

Is there any posibilty to add a linebreak in the title attribute?

**Comment by marcokreeft87** [comment]
You can try with template? Maybe some html in there.

**Comment by Holger-H** [comment]
This is a pity. Thanks for the really fast reply.

**Comment by marcokreeft87** [comment]
I was thinking, why don't you put the entities in entities in stead of info_entities? That's about the same result as putting a line break right?

**Comment by Holger-H** [comment]
The info_entities are really nice for some state information. I like design with the info entities top right.
I solved it for me by removing the title. I now use the icon to identify the room.
Your card is really nice. I think it's one of the best available card. Great work!

I think a way (config option) of enforcing the title on its own row would be an great improvement.

**Comment by marcokreeft87** [comment]
> The info_entities are really nice for some state information. I like design with the info entities top right.
> I solved it for me by removing the title. I now use the icon to identify the room.
> Your card is really nice. I think it's one of the best available card. Great work!
> 
> I think a way (config option) of enforcing the title on its own row would be an great improvement.

Thnx! 
Have you tried the template option I gave you?

**Comment by Holger-H** [comment]
No I did not try the template option.
