### ISSUE TITLE
Allow setting card background color

### ISSUE THREAD

**Issue by davefx** [marcokreeft87/room-card#117]
**Is your feature request related to a problem? Please describe.**
I currently have this dashboard using Lovelace Banner cards (https://github.com/crempp/banner-card) with a different colors for every room in the house. 
I'd love to replace it using room-cards, but I cannot find the way to set up a different background color for every room.

**Have you tried if it is already a feature? Have you checked the wiki?**
I've checked, and I cannot find the way. The styles directive doesn't seem to work.

**Describe the solution you'd like**
I'd love having two new configuration directives for every card: `background_color` and `text_color`  that receive a color in any format allowed in CSS.
It would be really nice if we also could different color directives for the title bar and for the space where entities are shown.

**Comment by marcokreeft87** [comment]
Please look at this:

https://github.com/marcokreeft87/room-card/discussions/100

You can do the same for the things you want to  do

**Comment by davefx** [comment]
I'm not really sure why, but it's not working. This is my room-card configuration:

```type: custom:room-card
title: Jardín delantero
styles:
  background-color: lightgreen;
info_entities:
  - entity: binary_sensor.detector_presencia_input
    show_icon: true
entities:
  - entity: light.fuente_entrada
  - entity: light.lampara_entrada
  - entity: light.luz_fachada_delantera
```
And this is what I'm getting:
![image](https://user-images.githubusercontent.com/292309/202970035-031b0947-52ce-48b3-9397-27517b6d6192.png)

**Comment by davefx** [comment]
I've checked that the `styles` attribute in the corresponding generated `<ha-card>` tag is empty.

**Comment by marcokreeft87** [comment]
Hmm can you try with an entity? So like a main entity if you know what I mean?
