### ISSUE TITLE
Mixing the room card with other cards gives a strange layout.

### ISSUE THREAD

**Issue by paulbusse** [marcokreeft87/room-card#121]
**Which version of Room Card?**
1.07.03

**Describe the bug**
Mixing the room card with other cards gives a strange layout. The expectation is that the three columns would have almost the same length.

**To Reproduce**
1. Create a HA card e.g. entities card
2. Create a  set of room cards.
3. The layout will not be balanced

**Expected behavior**
The columns should have similar length

**Screenshots**
![Screenshot from 2022-12-08 09-21-51](https://user-images.githubusercontent.com/38787377/206397460-cb03dc86-31cb-4852-b220-3e43eaa7b1e8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 107.0.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
Great work on this custom card!

**Comment by marcokreeft87** [comment]
Hey Paul, it might be too early, but I don't see an issue with the layout. Other than the card to the left is by itself.

Can you explain in more detail?

**Comment by paulbusse** [comment]
Let me explain a little differently. Lovelace puts the first card in the top left column. All the next cards are placed in the shortest-leftmost column. 
![3columns](https://user-images.githubusercontent.com/38787377/206499458-674690ec-740f-4e9c-9018-02643d438824.png)
The numbers on the different cards the order in which they are defined in the dashboard. If I reduce my screen so that lovelace goes to 2 columns, placement becomes
![2column](https://user-images.githubusercontent.com/38787377/206499430-cff13ad5-a442-4a56-8c91-99cd8ee2d0ea.png)
Because when lovelace wants to place the 5th card (the temperature graph) the shortest of the 2 columns is the right one. After that the RoomCard(6) is moved into the left column.

The above is what I'm expecting.

If I move the roomcard to the first position, lovelace distributes the cards like this.
![rcfirst](https://user-images.githubusercontent.com/38787377/206499483-32a2a5f6-ec03-40ea-8cf8-556ed2187ac8.png)
According to the algorithm, card 2 should go to the middle column. card 3 to the right one. But that doesn't happen.

IMHO...

When looking at  this [guide](https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/), lovelace expects a function `getCardSize`
```javascript
  // The height of your card. Home Assistant uses this to automatically
  // distribute all cards over the available columns.
  getCardSize() {
    return 3;
  }
```
A quick `grep` over your code did not find that function.
HTH 
PS. I'm based in Belgium

**Comment by marcokreeft87** [comment]
@paulbusse Check out v1.07.04. That includes the getCardSize

**Comment by paulbusse** [comment]
The screen looks already a lot better, but not perfect. Not all of it is caused by roomcard.
![Screenshot from 2022-12-09 10-28-05](https://user-images.githubusercontent.com/38787377/206671205-b0b5582b-0b1f-4c5c-b4c5-baa8a0df9808.png)

First, the card size of the modus card is calculated incorrectly. The horizontal stack just uses the max of the cards in it. However depending on the number of elements the horizontal stack reduces the size of the underlying cards.

I looked at your code again and I think there is a typo on `index.ts:103`.

Also I did a little analysis (it's what I do for a living, so couldn't help myself). A more correct calculation would contain.
* `hide_title == false`: add 1
* if entities present and for each row: add 1.5, if there is an entity which show state: add another 0.5 (2 in total)
* cards: call getCardSize on each of the cards
But as in the example with the horizontal stack above, calculations are not exact in other cards either. So, your choice on how far you want to go with this (obviously).

**Comment by marcokreeft87** [comment]
@paulbusse cards: call getCardSize on each of the cards. This will cause errors because not all cards have this method. And its no requirement on the interface unfortunately.
I've add the hide_title bool in the calculation. 
Im not sure about the half units tho, so I kept it to whole numbers.

**Comment by paulbusse** [comment]
This is ok for me. 

I really like this card and especially the templating. My batteries are configured as:

```yaml

        icon:
          template:
            icon: |
              if( entity.state == 100) return 'mdi:battery';
              let v = entity.state - (entity.state % 10);
              return 'mdi:battery-' + v;  
            styles: |
              return 'color: var(--green-red-flow--p' + (100 - entity.state) + ')';

```
Showing the different battery icons and a color slowly moving from red to green as they drain.

So thank you for building this
