### ISSUE TITLE
Update to room-card made my icon colors disapper

### ISSUE THREAD

**Issue by Ofir-P** [marcokreeft87/room-card#151]
Hey, I have updated to the latest version of the room-card, before that I had colors on the icons depending on the state of the entity.
After updating I can't see those colors anymore.

http://pastie.org/p/4V0r1KQr15lPoTzwl9BEvA

Any idea how can I fix that?

Thanks!

**Comment by marcokreeft87** [comment]
The pastebin url isn't working?

**Comment by marcokreeft87** [comment]
> > The pastebin url isn't working?
> 
> It's working for me, try this link:
> https://pastebin.com/b0upDADJ

That's working, but where in that yaml do you use room-card?

**Comment by Ofir-P** [comment]
> 

Thanks for the quick reply, I forgot to actually send the card itself.
https://pastebin.com/jxMbYL99

**Comment by marcokreeft87** [comment]
I only see card_room, no room-card? I think you are in the wrong repo

**Comment by Ofir-P** [comment]
> 

It's weird because as soon as I updated the repo my colors have been disappeared.
![image](https://user-images.githubusercontent.com/79255941/212835338-e56f9225-19aa-4812-bfc6-3999b114b6cb.png)

this is how the card looks like

**Comment by marcokreeft87** [comment]
Yeah that's not my card. That's the minimalist card. You are definitely in the wrong repo.
