### ISSUE TITLE
Card not working

### ISSUE THREAD

**Issue by brinkgit** [marcokreeft87/room-card#166]
**Which version of Room Card?** : 1.7.11

**Describe the bug**
I cannot use the card. It cannot be found in the card-selector

**To Reproduce**
No idea. Just did install via hacs, restart windows PC, started VM: no card to see.

**Expected behavior**
Working card

**Screenshots**
room-card is added via hacs
<img width="1638" alt="afbeelding" src="https://user-images.githubusercontent.com/46536975/217847051-59821063-fd25-49cb-9393-a75f93add7a8.png">

room-card cannot be found by the system
<img width="1109" alt="afbeelding" src="https://user-images.githubusercontent.com/46536975/217847156-a0b79878-2e41-4aec-929a-60c1e88165b9.png">

tried also via yaml:
<img width="1092" alt="afbeelding" src="https://user-images.githubusercontent.com/46536975/217848725-a4a0dc2f-07bc-4456-94b8-10ed9c8e4bfb.png">

**Desktop (please complete the following information):**
 - OS: windows10/VM
 - Browser firefox
**Additional context**

**Comment by marcokreeft87** [comment]
Try clearing the cache of your browser. If that doesn't help check Developer tools if the javascript file can be found.

**Comment by brinkgit** [comment]
I cleared cache, restarted, tried 2 other devices (iphone and ipad): no result.

Files are where I think they have to be:
www.comunity.room-card.room-card.js
and
www.comunity.room-card.room-card.js.gz

Don't know how to search fir files with developer tools.

**Comment by brinkgit** [comment]
Started all over.
Removed hacs, restart HA, cleared cache, load room-cards again via hacs, cleared cache, restart HA.

Now it works.

Thanks for your help!
