### ISSUE TITLE
[Feature Request] hold_action and double_tap_action

### ISSUE THREAD

**Issue by usernein** [marcokreeft87/room-card#18]
What a pretty card! It's nice to have tap_action to toggle, specially since you have implemented haptics, but i still miss hold_action (i don't really care about `double_tap_action`, i just included it here because i thought it was right to put these 2 in the same feature request)
I use hold_action a lot in my current dashboard based on mushroom.

Also, please consider making the time to trigger hold_action configurable. I miss it so much in mushroom cards but its dev [doesn't like the idea](https://github.com/piitaya/lovelace-mushroom/issues/593#issuecomment-1178792485)

**Comment by daballiemo** [comment]
+1 for hold_action. Double tap brings the info up but also switches lights to on... As I am using custom button card which has the hold_action it would be nice to use this card with the same commands.

**Comment by marcokreeft87** [comment]
@daballiemo I'm trying to find a good way to do this but precisely because of the double click behavior you have I say the double tap is use on own risk. On mobile there is really not an easy way to catch the double tap and hold, because, how long do you wait between taps or till you release your finger (for hold).

But I will keep trying

**Comment by daballiemo** [comment]
> 

Maybe have a look at the sourcecode of the custom button card? Works for me in browser, browser on IOS and app on IOS

**Comment by marcokreeft87** [comment]
Thats a good one! Now I have to find the time to do it :P

**Comment by marcokreeft87** [comment]
@usernein @daballiemo can you check out version 1.2.2 and test the hold_action?

**Comment by daballiemo** [comment]
@marcokreeft87 
works like a charm for me. Without specifing the hold_action I get the detail screen. When specifing the hold_action the sky is the limit especially when combining it with browser_mod.popup Thx a million!

**Comment by marcokreeft87** [comment]
No problem, was a nice excuse to learn something new
