### ISSUE TITLE
Wrong alignment on mobile

### ISSUE THREAD

**Issue by fellipute** [marcokreeft87/room-card#2]
It seems that when I put entities in the card the alignment is off in the mobile app:

![IMG_20220429_131402](https://user-images.githubusercontent.com/3584098/165983454-db0734ac-17af-4e72-ac8f-78859e39cfbf.jpg)

**Comment by marcokreeft87** [comment]
Hmm that's weird. Can you send the yaml and which theme you use?

**Comment by fellipute** [comment]
Thanks!

I think its related to the mobile app cause I tried on chrome using the mobile viewport and it shows correctly using the same theme:

![image](https://user-images.githubusercontent.com/3584098/166115164-3535fc36-dd08-46c2-83b3-be7c8d7866ea.png)

**Comment by marcokreeft87** [comment]
> Thanks!
> 
> I think its related to the mobile app cause I tried on chrome using the mobile viewport and it shows correctly using the same theme:
> 
> ![image](https://user-images.githubusercontent.com/3584098/166115164-3535fc36-dd08-46c2-83b3-be7c8d7866ea.png)
> 

In that screenshot you can also see some additional padding. But let's see Monday. I hope it's easy to fix :)

**Comment by marcokreeft87** [comment]
@fellipute I don't have the issue sadly. So I cant help you :(
![Screenshot_20220502-102618_Home Assistant](https://user-images.githubusercontent.com/10223677/166206215-6f7733a6-287b-4f9d-bdc1-747d6064985b.jpg)

**Comment by marcokreeft87** [comment]
![Screenshot_20220502-102618_Home Assistant](https://user-images.githubusercontent.com/10223677/166206414-25ae66f5-8b51-4cb4-9086-74ea60f9fc1a.jpg)

**Comment by marcokreeft87** [comment]
@fellipute Sadly I dont have the issue, see post above, so Im not able to help you :(

Dont mind the icons overflowing btw, I was trying some things to reproduce your issue.

Do you have the latest version of the app and the theme?

**Comment by labaland** [comment]
fuck me, just spent 2-3 hours to add my enteties to show my mobile wiew with room-card.
and when im almost done i check it on the phone and it looks like shit.. text and enteties above each other..
nice.
