### ISSUE TITLE
Icon Template: Changing the value of an entity instead of comparing it

### ISSUE THREAD

**Issue by aIexus** [marcokreeft87/room-card#209]
**Which version of Room Card?**
1.07.20

**Describe the bug**
I'm trying to use icon template and faced with an issue - during comparing entity state with some value I have changed value of entity.

**To Reproduce**
1. Have some value template for your room card, e.g.:
...
 ```
         - type: custom:room-card
            title: null
            icon: mdi:meter-electric
            show_icon: true
            entity: sensor.energy_counter_total
            tap_action: none
            double_tap_action: none
            info_entities:
              - entity: sensor.tuya_clamp_meter_power
                format: precision1
              - entity: sensor.tuya_clamp_meter_current
                format: precision1
              - entity: sensor.tuya_clamp_meter_voltage
                format: precision1
              - entity: sensor.energy_active_tariff
                show_icon: true
                icon:
                    template:
                        icon: >
                          if (entity.state = 'day'  ) return 'mdi:weather-sunny';  
                          if (entity.state = 'night') return 'mdi:power-sleep';  
                          else return 'mdi:counter';
```
**Expected behavior**
Depending on the state of sensor.energy_active_tariff icon will be changed: for 'day' -> 'mdi:weather-sunny', for 'night' -> 'mdi:power-sleep'.

**Screenshots**
![image](https://user-images.githubusercontent.com/96982465/229713610-11432390-acc3-402e-89db-cf080703a325.png)

![image](https://user-images.githubusercontent.com/96982465/229713721-5aac22c9-4a3c-4942-b94b-3256cb83423e.png)

![image](https://user-images.githubusercontent.com/96982465/229713806-459205f2-22c0-4468-ae18-840a4309d3e9.png)

![image](https://user-images.githubusercontent.com/96982465/229714392-d8dc0d9b-b826-4237-b45c-7b8ad79c8522.png)

**Desktop (please complete the following information):**
 - Browsers: 
   - chrome 111.0.5563.147 (Official Build) (64-bit)
   - firefox 111.0.1 (64-bit)

**Comment by marcokreeft87** [comment]
Try == in stead of =. A single = sets the value.

**Comment by aIexus** [comment]
> Try == in stead of =. A single = sets the value, double compares in javascript

It's strange. Yesterday I played with this operator and had no success. But now it works.
Sorry for disturbing you. :)
