### ISSUE TITLE
Cannot change entity status font-size style

### ISSUE THREAD

**Issue by davefx** [marcokreeft87/room-card#227]
**Which version of Room Card?**
1.07.20

**Describe the bug**
I'm trying to set the font-size for an entity status, but it cannot be overwritten.

**To Reproduce**
1. I'm trying to change the size of the shown status in one of the entities:
```      - entity: counter.contador_secados_tras_limpieza_filtro
        show_icon: false
        show_state: true
        show_name: false
        name: Secados tras última limpieza filtro
        styles:
          width: 40%
          text-align: center
          font-weight: "bold !important"
          font-size: "x-large !important"
```
2. See error:
![imagen](https://user-images.githubusercontent.com/292309/236382218-494e32e8-1f68-40ef-b244-f771b71f5b1b.png)

3. I see that the CSS font-size is overwritten for the span child and set to 10px.

**Expected behavior**
I would have expected to be able to customize the size of this entity status.

**Desktop (please complete the following information):**
 - OS: Linux 
 - Browser: Chrome and Firefox

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Android
 - Browser: Firefox

**Additional context**
I've debugged the CSS for the element, and I see that we have a fixed font-size for the class `.entity span`, that doesn't seem to be customizable at all:

![imagen](https://user-images.githubusercontent.com/292309/236382737-f3ee8c3b-55e1-427d-a849-7228797876f3.png)

**Comment by marcokreeft87** [comment]
This isn't a bug, but I'll look at it when I can

**Comment by marcokreeft87** [comment]
The styles you want to apply can't be applied like you do. 
You'll need card_mod for that
