### ISSUE TITLE
Navigation header url not working with 1.07.21

### ISSUE THREAD

**Issue by FreddyX078** [marcokreeft87/room-card#232]
**Which version of Room Card?**
1.07.21

**Describe the bug**
After update to 1.07.21, navigation header url not working.

**To Reproduce**
1. Create a card like below.
2. Click on the title 'Solar'
3. See error in log

`type: custom:room-card
title: Solar
entity: sun.sun
show_icon: true
tap_action:
  action: navigate
  navigation_path: /lovelace/solar`

** Error in log:
2023-05-17 08:17:32.298 ERROR (MainThread) [frontend.js.latest.202305033] http://192.168.x.x:8xx3/hacsfiles/room-card/room-card.js?hacstag=45444094910721:21:315 TypeError: undefined is not an object (evaluating 't.action')

**Expected behavior**
Navigate to url (/lovelace/solar)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Safari
 - Version: 16.4

**Additional context**
Redownloaded version 1.07.20 and this version is working as expected.
I've also an entity under entities with an navigation url and this one is oké.
Only in the header it is not working with 1.07.21.

**Comment by marcokreeft87** [comment]
Should be fixed in 1.07.22

**Comment by FreddyX078** [comment]
Thanks! Fixed very fast 😃
