### ISSUE TITLE
Unable to use tap_action in entity icon (header)

### ISSUE THREAD

**Issue by cobirnm** [marcokreeft87/room-card#236]
**Which version of Room Card?**
1.07.21 and 1.07.22

**Describe the bug**
Unable to use tap_action in entity icon (header)

**To Reproduce**
1) click on main entity icon
2) see that nothing happens

**Expected behavior**

**Screenshots**
![image](https://github.com/marcokreeft87/room-card/assets/45829329/6619c4e7-d325-480a-84b6-dcdf54b8f7c2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcokreeft87** [comment]
Should be fixed in 1.07.23

**Comment by cobirnm** [comment]
> 

I confirm that it has been fixed. Thank you
