### ISSUE TITLE
Cards updating too frequently and causing an annoying flickering / flashing issue with frigate-card

### ISSUE THREAD

**Issue by ndbroadbent** [marcokreeft87/room-card#245]
**Which version of Room Card?**

`1.07.23`

**Describe the bug**

I am using `custom:frigate-card` to show some images for my cameras, under the `cards:` option. I noticed that this card seems to be getting constantly reloaded whenever any of the other entities are updated (e.g. garage door sensor, motion sensor.) This causes a really annoying flickering issue where the camera card keeps reloading multiple times per second.

See video: https://www.youtube.com/watch?v=YOoKUxbk1d8

**To Reproduce**

1. See video: https://www.youtube.com/watch?v=YOoKUxbk1d8

**Expected behavior**

The card should not be refreshed if other state changes, or there should be an option to make it more persistent.

**Screenshots**

https://www.youtube.com/watch?v=YOoKUxbk1d8

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcokreeft87** [comment]
Sorry but there is nothing I can do about that. That's just how HA passes info to cards.
