### ISSUE TITLE
Larger Icon, independent of entity

### ISSUE THREAD

**Issue by ecraven** [marcokreeft87/room-card#257]
**Is your feature request related to a problem? Please describe.**
I really like the larger icons that the default HA room card has to show *what* is shown on the card (but all the other features are so much better on this one!)

**Have you tried if it is already a feature? Have you checked the wiki?**
I've tried to not set an entity, but set an icon, and whenever there is no entity set, no icon is shown.

**Describe the solution you'd like**
I would love a way to show an icon (ideally even in a given color, to make the rooms more different), independent of any entity, in the upper left corner. maybe even with a bit of a circle around it.

**Additional context**
Excuse my poor graphics abilities, but I'm imagining something like this:

![sample](https://github.com/marcokreeft87/room-card/assets/215510/39bf6159-8dd1-4f67-89e9-86d715c4cc2b)

This could be done by just showing the icon like this if *no* entity is set on the card, but show it normally *if* an entity is set. Is this something that would be ok to create a PR for?

Thanks for such a great card!

**Comment by marcokreeft87** [comment]
Sorry but I don't have enough time to add features to the card
