### ISSUE TITLE
Both icon and state in info entities

### ISSUE THREAD

**Issue by metbril** [marcokreeft87/room-card#268]
Currently, the info entities row can show an icon OR the state (text). I would like to have the possibility to show both (show_state: true AND show_icon: true). The use case for this is when you have multiple sensors with similar values that you want to show. For example multiple percentages. An additional icon would be nice to distinguish both.

**Comment by marcokreeft87** [comment]
The problem is that there isn't that much room. So both won't be visual pleasing. I would recommend using different icons.

**Comment by metbril** [comment]
Visually pleasing or not is to the user. ;-) As long as it's optional to pick one or both. A workaround would be to add each sensor twice, but I prefer to prevent having to do that.

**Comment by marcokreeft87** [comment]
True, but I try to keep to the designed purpose of the card
