### ISSUE TITLE
Error cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by cherryocola** [marcokreeft87/room-card#269]
**Which version of Room Card?**
1.07.25

**Describe the bug**
Random error message "Cannot read properties of undefined (reading 'style')" on one of the cards everytime I open the main page.
I get these on both the browser and companion app. 
It pops up around 50% of the time.

**To Reproduce**
Dont know.

**Expected behavior**

**Screenshots**
<img width="542" alt="Cannot read properties" src="https://github.com/marcokreeft87/room-card/assets/36471982/2692bbcd-a998-445c-b054-a573007ac514">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows/ Android
 - Browser [e.g. chrome, safari] Chrome/ Companion App

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcokreeft87** [comment]
Do you have template entities? It got to do with the timing when entities are available. I really can't do much to help you with this except for giving you some hints where to look

**Comment by cherryocola** [comment]
> Do you have template entities? It got to do with the timing when entities are available. I really can't do much to help you with this except for giving you some hints where to look

Hi, no Template Entities. Heres the whole card.

type: custom:room-card
title: 客廳
info_entities:
  - entity: input_boolean.someone_is_home_wifi
    hold_action:
      action: toggle
    icon: mdi:home-import-outline
    show_icon: true
    state_color: true
  - entity: input_boolean.simulated_night_switch
    hold_action:
      action: toggle
    icon: mdi:bed-clock
    show_icon: true
    state_color: true
rows:
  - entities:
      - entity: light.magic_switch_s1e_b001_switch_3
        name: 天花燈
        icon: mdi:chandelier
        tap_action:
          action: toggle
        show_icon: true
        state_color: true
      - entity: light.magic_switch_s1e_b001_switch_1
        name: 牆射燈
        icon: mdi:light-flood-down
        tap_action:
          action: toggle
        show_icon: true
        state_color: true
      - entity: light.living_room_entrance_lights
        name: 鞋櫃燈
        secondary_info: brightness
        icon: mdi:led-strip-variant
        tap_action:
          action: toggle
        show_icon: true
        state_color: true
      - entity: switch.table_entrance_lights_l1
        name: 飯檯燈
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
        show_icon: true
        state_color: true
  - entities:
      - entity: switch.living_room_air_conditioner_2
        name: 冷氣機
        icon: mdi:air-conditioner
        hold_action:
          action: toggle
        show_icon: true
        state_color: true
      - entity: media_player.sony_kd_55x9000e
        name: Sony TV
        icon: mdi:television
        show_icon: true
        state_color: true
      - entity: input_boolean.living_room_tv_in_out
        name: 電視臂
        icon: mdi:swap-horizontal
        hold_action:
          action: toggle
        show_icon: true
        state_color: true
      - entity: light.living_room_tv_led
        secondary_info: brightness
        name: 電視 LED
        icon: mdi:led-strip-variant
        tap_action:
          action: toggle
        show_icon: true
        state_color: true
      - entity: switch.0xa4c138a4a323b554
        name: PS5 散熱
        icon: mdi:fan
        tap_action:
          action: toggle
        state_color: true
        show_icon: true
        hide_if:
          conditions:
            - condition: equals
              value: 'off'
            - condition: equals
              value: unavailable
      - entity: media_player.living_room_speaker
        icon: mdi:google-assistant
        name: Google
        tap_action:
          action: toggle
        state_color: true
        show_icon: true
        hide_if:
          conditions:
            - condition: equals
              value: 'off'
      - entity: switch.ps5_567_power
        icon: mdi:sony-playstation
        name: PS5
        tap_action:
          action: toggle
        state_color: true
        hide_if:
          conditions:
            - condition: equals
              value: unavailable
cards:
  - type: custom:mini-media-player
    entity: media_player.sony_kd_55x9000e
    volume_stateless: true
    hide_if:
      conditions:
        - condition: equals
          value: 'off'
        - condition: equals
          value: unavailable
  - type: custom:mini-media-player
    entity: media_player.living_room_speaker
    volume_stateless: true
    hide_if:
      conditions:
        - condition: equals
          value: 'off'
        - condition: equals
          value: unavailable

Any ideas? thanks in advance

**Comment by cherryocola** [comment]
Ok, I think its the custom:mini-media-player cause it doesnt happen when its hidden.
Any idea how I could solve this? thanks

**Comment by marcokreeft87** [comment]
Might be the unavailable condition for hiding. Not sure

**Comment by marcokreeft87** [comment]
@cherryocola   can you test it with v1.08.00 thanks to Scott ( don't know your github handle bro ) it should be fixed :)

**Comment by marcokreeft87** [comment]
@cherryocola try v1.08.01 xD It's going fast

**Comment by elninosi** [comment]
Works for me. Thank you very much for fixing this bug.
