### ISSUE TITLE
Certain Icons/Cards not responding to conditions

### ISSUE THREAD

**Issue by BentleySmarthome** [marcokreeft87/room-card#270]
**Which version of Room Card?**
1.07.25

**Describe the bug**
After the HA update yesterday, many things not responding to style and hide conditions that worked prior to the update. What I have noticed thus far:
Lights, media players, vacuums, Zigbee/Zwave switches, and door sensor seem to work fine.
Helpers (input Boolean serving as pseudo switches), Wyze switches, and Smart Things (switches, sensors, etc) appliances do not seem to respond despite being the correct states to trigger the conditions.

**To Reproduce**
Easiest to reproduce would be to create an input boolean helper and set a condition based on being on or off. Tried several combinations in case I was messing something up, true/false, on/off, state_on, state_off etc.
![image](https://github.com/marcokreeft87/room-card/assets/145469115/30ff8798-0be2-4a40-a750-194d1ff40c2e)

**Expected behavior**
Prior to the update, all conditions, including hides I was using on the same switches for hiding/unhiding addition cards were working as intended. The almost is covered by swapping icons to orange when on/open/running, etc. There were also a few hide/unhide.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome: 
 - Version [e.g. 22] 117.0.5938.132

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Max
 - OS: 17.0.2
 - Browser: HA App
 - Version: latest

**Additional context**
Otherwise been loving using this in my interface, great work!

**Comment by marcokreeft87** [comment]
Yes, it's been a while but if I'm not mistaken input_booleans won't work

**Comment by BentleySmarthome** [comment]
@marcokreeft87  Same thing unfortunately:
![image](https://github.com/marcokreeft87/room-card/assets/145469115/d3a264d9-d4e7-4b4d-8a7a-24b2bda0834d)

**Comment by marcokreeft87** [comment]
Do you have other input_booleans with the same configuration? Do they work?

**Comment by BentleySmarthome** [comment]
![image](https://github.com/marcokreeft87/room-card/assets/145469115/ffb95828-b70c-433d-b9ca-a02e5f65c2f3)
Same thing - i created a test one just to eliminate everything else from the mix.

**Comment by marcokreeft87** [comment]
I think something changed for input_booleans. I will take a look when I have time

**Comment by marcokreeft87** [comment]
I think you are missing something in your configuration:

**Comment by BentleySmarthome** [comment]
Icon is in most of the configurations, as well as required show_icon, below is from that same test case with an icon that works w/ other entities.

![image](https://github.com/marcokreeft87/room-card/assets/145469115/66462a85-35db-4d30-af31-ab91412dd50e)

**Comment by BentleySmarthome** [comment]
Here are some of the others that worked prior to yesterday. So Helper, then Wyze Plug, then Samsung Fridge Contact sensor. Current Values are On, On, and Open in this image. Hope it helps:
![image](https://github.com/marcokreeft87/room-card/assets/145469115/144a3d6c-5efa-4af5-b5a1-8f152eca24cd)

**Comment by marcokreeft87** [comment]
Plz check the docs: 

    https://github.com/marcokreeft87/room-card/wiki/Configuration#icon-conditions

**Comment by BentleySmarthome** [comment]
No change:
![image](https://github.com/marcokreeft87/room-card/assets/145469115/02d9a53f-b89a-4e0b-bf35-f7e8d81b8b30)

**Comment by marcokreeft87** [comment]
It shouldn't matter, but if you start the condition with  condition in stead of icon? 

It's working on my HA instance, the same configuration but different entities ofcourse. So if that doesn't work, I'm clueless.

Wish I could remote debug your HA

**Comment by BentleySmarthome** [comment]
Thanks for trying. I guess ill just have rebuild my interface to exclude these.

**Comment by BentleySmarthome** [comment]
I figured it out :)

**Comment by marcokreeft87** [comment]
> I figured it out :)

Show me!
