### ISSUE TITLE
Request: Multi Rows for info_entities

### ISSUE THREAD

**Issue by Bjoern3003** [marcokreeft87/room-card#275]
Hi,

could be nice, to use multi Rows for info_entities.

I am displaying the humidity, temperature and pressure in info_entities. In order to make better use of the space, it would be helpful to display these values one below the other.

![1697279498](https://github.com/marcokreeft87/room-card/assets/13675579/d25fb8de-9373-4207-b671-c360c7767f09)

**Comment by marcokreeft87** [comment]
Sorry but thats not what the card is designed for.  You could try with card_mod?
