### ISSUE TITLE
hide_if shorthand broke after 1.2.2

### ISSUE THREAD

**Issue by theOrakle** [marcokreeft87/room-card#30]
**Describe the bug**
If you use basic functionality of
`hide_if: 'on'` or
`hide_if: 'off'`
on versions 1.2.3 to 1.2.6 , it hides the whole card.

**To Reproduce**
1. Upgrade 1.2.3 - 1.2.62. 
2. Have shorthand described above (and in the config doc)
3. Card disappears

**Expected behavior**
Short hand config to still be valid.  I can rewrite all my hides to work in the new config (conditions), but the config doc still had the shorthand, so I thought I would bring it to your attention.

**Screenshots**
N/A

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
N/A

**Comment by marcokreeft87** [comment]
Hiding config changed. Check https://github.com/marcokreeft87/room-card/wiki/Configuration#hiding

**Comment by marcokreeft87** [comment]
O good one. But the code works like the example. Sorry about the docs being old dated

**Comment by marcokreeft87** [comment]
Just killed it. Thnx!
