### ISSUE TITLE
cannot get background-image to work

### ISSUE THREAD

**Issue by RedNo7** [marcokreeft87/room-card#306]
**Which version of Room Card?**
1.08.02

**Describe the bug**
I have an image: /www/images/hallway.jpg

When I use it in a picture card it works, but when I use its in custom:room-card, it doesn't:

**Screenshots**
![Screenshot 2024-01-28 at 11 56 35](https://github.com/marcokreeft87/room-card/assets/130979051/31b74b2d-1fb3-4653-894e-842f02a1ed7c)

**Desktop (please complete the following information):**
 - OS: MacOS, iOS
 - Browser:
    - Safari v17.3
    - Brave v1.62.153 
    - Firefox v122.0

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.3
 - Browser Safari

**Additional context**

**YAML**
```yaml
- type: picture
  image: /local/images/hallway.jpg
```

```yaml
- type: custom:room-card
  entity: light.hallway
  styles:
    background-image: url('/local/images/hallway.jpg')
  ...

**Comment by marcokreeft87** [comment]
You need to use card_styles in stead of styles. The styles will be applied to the entity and not the card.
