### ISSUE TITLE
Unable to reduce minimum padding between elements or reduce minimum size.

### ISSUE THREAD

**Issue by Andrewpaps** [marcokreeft87/room-card#31]
Unable to reduce size of buttons so that they appear closer together and more can fit on one row without snapping to next row.

Should be able to reduce distance between buttons/size of buttons with CSS.

![image](https://user-images.githubusercontent.com/71562383/189189044-e49459d6-5ddb-4600-96c0-0d070ca7c3d9.png)

Causing the following unwanted behaviour:

![image](https://user-images.githubusercontent.com/71562383/189189736-7a102d64-fffe-4090-a9ca-568611036542.png)

Occurring on all platforms including Windows, MacOS & iOS on iPhone 8.

**Comment by marcokreeft87** [comment]
Try the card mod plugin. Room card wont support that in the near future, sorry
