### ISSUE TITLE
tap action on background image

### ISSUE THREAD

**Issue by pvklink** [marcokreeft87/room-card#312]
Is it possible to make a tap action on the backround image?
I like to use the room card as an alternative for the default lovelace are card.
The areacard hs the functionality to click on the area image...

                  - type: custom:room-card
                    title: Huiskamer custroom
                    entity: light.ac_0e672c2_9
                    tap_action:
                      action: navigate
                      navigation_path: Huiskamer
                    show_icon: true
                    icon: mdi:lightbulb-outline
                    info_entities:
                      - entity: binary_sensor.x10_security_motion_detector_ade400_32
                        show_icon: true
                        tap_action:
                          action: call-service
                          service: input_boolean.toggle
                          target:
                            entity_id: input_boolean.reset_motion
                        icon:
                          conditions:
                            - condition: equals
                              value: 'on'
                              styles:
                                color: red
                            - condition: equals
                              value: 'off'
                              styles:
                                color: rgba(175,175,175,1)
                    card_mod:
                      style: |
                        ha-card {
                          height: 175px;
                          .title {font-size: 20px;font-weight: 400};
                          background: url("/local/images/huiskamer.jpg");                     
                          background-size: cover;
                        }

**Comment by marcokreeft87** [comment]
That would be confusing behavior. Don't see the added value in it sorry
