### ISSUE TITLE
Can no longer remove title of elements with 'name: false'

### ISSUE THREAD

**Issue by Andrewpaps** [marcokreeft87/room-card#32]
Used to be able to remove titles with 'name: false' but no longer works. 

Perhaps a proper feature to disable titles is necessary. This is helpful to reduce the height of a row when icons are self-explanatory.

Current behaviour:

![image](https://user-images.githubusercontent.com/71562383/189190146-f687144a-b5dc-46a0-99e0-33bcdbdfb9dc.png)

Desired behaviour:

![image](https://user-images.githubusercontent.com/71562383/189190221-a05b9997-7d65-44a6-84c2-7b793a614b55.png)

Occurring on all platforms.

**Comment by marcokreeft87** [comment]
Hide_title: true should work. Isn't it in the docs? If so I will put it in there.

**Comment by marcokreeft87** [comment]
Good idea!

**Comment by marcokreeft87** [comment]
@Andrewpaps  Try version 1.2.7 and try the show_name: false config

**Comment by Andrewpaps** [comment]
Yep, tested and working as of 1.2.7. Lightning quick response - excellent work.
