### ISSUE TITLE
style templating of binary_sensor, state not matching

### ISSUE THREAD

**Issue by idkpmiller** [marcokreeft87/room-card#331]
**Which version of Room Card?**
1.08.04

**Describe the bug**
Using the4 configuration guide as an example for the template styles. The example shows a switch entity, I would like to make some icon changes to a binary_sensor entity. I heve the following yaml, and the 'Windows' entity always falls through to the default outcome if no match is fouund for both color and iicon used. 
I have trid matches of the state as
off, Off, OFF, closed, Closed and CLOSED
None of these create a match.

**To Reproduce**

use the following yaml

      - entity: binary_sensor.office_windows
        icon:
          template:
            styles: >
              if (entity.state == 'off') return 'color: blue';  
              if (entity.state == 'on') return 'color: yellow';  
              else return 'color: white';
            icon: >
              if (entity.state == 'off') return 'mdi:window-closed';  
              if (entity.state == 'on') return 'mdi:window-open';  
              else return 'mdi:window-shutter-auto';
        show_icon: true
        name: Windows

**Expected behavior**
When the windows grrop state is Open then the color of the icon should be yello and the icon displayed should be for window-open. When they are closed the icon should be blue and the icon should be window-closed.
the white colow and the neither stae is always being displayed when the cuurrent state of the group entitiy is Closed or Open.

**YAML**

type: custom:room-card
title: Office
entity: binary_sensor.office_epl_occupancy
icon: mdi:motion-sensor
show_icon: true
info_entities:
  - entity: sensor.office_epl_illuminance
    format: precision0
  - entity: sensor.office_humidity
    format: precision0
  - entity: sensor.office_temperature

rows:
  - entities:
      - entity: light.office
        icon: mdi:ceiling-light
        show_icon: true
        name: Light
        tap_action:
          action: toggle
      - entity: fan.office
        icon: mdi:ceiling-fan
        show_icon: true
        name: Fan
        tap_action:
          action: toggle
      - entity: switch.office_heater
        icon: mdi:radiator
        show_icon: true
        name: Heater
        tap_action:
          action: toggle
      - entity: switch.office_dehumidifier
        icon: mdi:air-humidifier-off
        show_icon: true
        name: Dehumidifier
        tap_action:
          action: toggle
      - entity: input_boolean.office_hvac
        icon: mdi:hvac
        show_icon: true
        name: HVAC
        tap_action:
          action: toggle
      - entity: binary_sensor.office_windows
        icon:
          template:
            styles: >
              if (entity.state == 'off') return 'color: blue';  
              if (entity.state == 'on') return 'color: yellow';  
              else return 'color: white';
            icon: >
              if (entity.state == 'off') return 'mdi:window-closed';  
              if (entity.state == 'on') return 'mdi:window-open';  
              else return 'mdi:window-shutter-auto';
        show_icon: true
        name: Windows

**Comment by marcokreeft87** [comment]
Hey! Check out :
https://github.com/marcokreeft87/room-card/wiki/Configuration#icon and especially the icon conditions

**Comment by idkpmiller** [comment]
Managed to fix it, not exactly sure how, but happy its working. I am sorry but I fing the configuration guide of limited assistance due to its form.
I seem to have to muddle my way through.
Thanks for an excellant card
Paul
