### ISSUE TITLE
Problem with Firefox 129.0.1 (64bit)

### ISSUE THREAD

**Issue by coasting24** [marcokreeft87/room-card#342]
**Which version of Room Card?**
1.08.04

**Describe the bug**

A view which contains a room_card is closed by Firefox 129.0.1 on Windows11 within 1-2 seconds. A page with button requesting a reload of the UI is shown instead, but without any reaction.  

The following warning is shown in the home-assistant.log:

WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [545699161584] XXXX from xxx.xxx.xxx.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0): Disconnected: Received non-Text message.

The same dashboard view is shown on Chrome w/o any problem.

**Comment by marcokreeft87** [comment]
This doesn't seem to be related to room-card tbh. The card doesn't do websocket calls. It just uses data it gets from HA.
