### ISSUE TITLE
Multi-line formatting for informational entities

### ISSUE THREAD

**Issue by p1ne** [marcokreeft87/room-card#35]
**Is your feature request related to a problem? Please describe.**
Is seems good to allow to organize informational entities in two rows or in table form. E.g. to have temperature and humidity values one above the other and/or just divide perception entities with security related entities

**Describe the solution you'd like**
To provide parameter with number of rows or ability to define table of infomational values via yaml nesting

**Describe alternatives you've considered**
CSS?

**Additional context**
None

**Comment by marcokreeft87** [comment]
Check version 1.3.0
https://github.com/marcokreeft87/room-card/wiki/Configuration#rows

**Comment by p1ne** [comment]
Disagree with closure, as request is for info_entities, not for entities. E.g. to have temperature above humidity and/or to have longer statuses in 2nd line

**Comment by marcokreeft87** [comment]
Hmm but why would you want that? That would look weird because the info entities row is made to be one row. I will check if I can make that look good.

**Comment by p1ne** [comment]
I see formatting problems on mobile device, that's why I would like to have the possibility to compact infomation in rows

![telegram-cloud-photo-size-2-5255963222459137660-y](https://user-images.githubusercontent.com/8995611/189526633-9166e8ba-4f9b-4778-8c8a-04d1ffa7b4c6.jpg)

**Comment by marcokreeft87** [comment]
Sorry that's a won't do for me. Maybe You can try something with card mod. The info entity row is designed for one row only. You can try to use icons in stead of text.

**Comment by mihsu81** [comment]
@p1ne You can adjust the font size of the title and the vertical position of entities-info-row.
This is what I used:
```yaml
style: |
  .card-header {
    font-size: 15px !important;
  }
  div.entities-info-row {
    padding-right: 0px;
    top: 11px;
  }
```

**Comment by yapishkahilt** [comment]
> @p1ne You can adjust the font size of the title and the vertical position of entities-info-row. This is what I used:
> 
> ```yaml
> style: |
>   .card-header {
>     font-size: 15px !important;
>   }
>   div.entities-info-row {
>     padding-right: 0px;
>     top: 11px;
>   }
> ```

This is exactly what I was looking to do and works perfectly. Thank you
