### ISSUE TITLE
Can the Title font size be reduced?

### ISSUE THREAD

**Issue by templeowls21** [marcokreeft87/room-card#350]
See question above. The font is a bit too big for my dashboard. Any way to alter it via card mod or another method?

**Comment by marcokreeft87** [comment]
Did you read the wiki by any chance? :p

**Comment by templeowls21** [comment]
Here? https://github.com/marcokreeft87/room-card/wiki/Configuration

I did, I don't see anything on title font size unless I'm missing it

**Comment by marcokreeft87** [comment]
Yes, the styles section

**Comment by templeowls21** [comment]
There is nothing about font size for the title in the styles section. I'll look for another method. Thanks tho.

**Comment by marcokreeft87** [comment]
You have to know how to apply custom css or use card_mod. I can't teach you through Github discussions. Look up some home assistant community examples.

**Comment by templeowls21** [comment]
I know how to use card_mod; I just can't seem to figure out the naming convention for the title attribute

**Comment by marcokreeft87** [comment]
There is title css class, does that help?

**Comment by templeowls21** [comment]
It did! THanks!
