### ISSUE TITLE
show_state doesn't hide title entity's state

### ISSUE THREAD

**Issue by laurisleitans** [marcokreeft87/room-card#36]
**Describe the bug**
`show_state: false` does't hide the state of the main/title entity.

**To Reproduce**
Example code:
```
type: custom:room-card
title: Test
entity: sun.sun
show_state: false
```
gives entity state before "Test".

**Expected behavior**
The entity state not appearing, just the title.

**Screenshots**
-

**Desktop (please complete the following information):**
Version 1.3.1

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by marcokreeft87** [comment]
Fixed with version 1.3.2
