### ISSUE TITLE
Entity object requires at least one 'entity', 'attribute' or 'icon'.

### ISSUE THREAD

**Issue by aletzi1** [marcokreeft87/room-card#40]
**Describe the bug**
After updating from 1.3.0 to 1.3.3 my Room Card stopped working. Tried to dowgrade from 1.3.3 to 1.3.0, does not work anymore.

**Screenshots**

![room card](https://user-images.githubusercontent.com/66028464/189498529-28ff1fe7-1c25-4707-ba49-5e988bd73888.jpg)

**Desktop:**
 - OS: Windows 11
 - Browser: Edge, Chrome

**Smartphone:**
 - Device: Oneplus 8T
 - OS: Android 11
 - Browser: Chrome and  Home Assistant app

**Comment by marcokreeft87** [comment]
I think you gotta downgrade to a lower version than 1.3.0 for now. I will look at the bug.

**Comment by marcokreeft87** [comment]
Should be fixed with v1.3.4. Was an easy fix :)

**Comment by aletzi1** [comment]
I can confirm its working now, thanks :)
