### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by AndyLuz** [marcokreeft87/room-card#46]
Hello
I have a problem with refreshing of this card.  If I turn on the light the state of the card changes after about 5 seconds. I also had power graph and it also refreshes at about 5 sec rate. What could be the problem?

This is my card:
type: custom:room-card
title: Office
info_entities:
  - entity: sensor.eye_office_air_temperature
    show_icon: 0
    state_color: true
  - entity: sensor.eye_office_illuminance
    show_icon: 0
    state_color: true
  - entity: binary_sensor.eye_office_home_security_motion_detection
    show_icon: true
    state_color: true
    icon: mdi:motion-sensor
  - entity: binary_sensor.window_office_contact
    show_icon: true
    state_color: true
    icon:
      state_on: mdi:window-open-variant
      state_off: mdi:window-closed-variant
cards:
  - type: grid
    square: false
    columns: 3
    cards:
      - type: custom:button-card
        entity: switch.light_pisarna
        color_type: icon
        color: auto
        state:
          - value: 'on'
            icon: mdi:lightbulb-on
          - value: 'off'
            icon: mdi:lightbulb
        name: Light
        size: 20%
        tap_action:
          haptic: selection
          action: toggle
      - type: custom:button-card
        entity: switch.light_office1
        color_type: icon
        color: auto
        state:
          - value: 'on'
            icon: mdi:lightbulb-on
          - value: 'off'
            icon: mdi:lightbulb
        name: Light 1
        size: 20%
        tap_action:
          haptic: selection
          action: toggle
      - type: custom:button-card
        entity: camera.camera_office_profile000
        name: Camera
        size: 20%

**Comment by marcokreeft87** [comment]
The card refreshes when HASS passes changes. I have the same problem with some lights. Not all. Thats the weird part.. Dont think this is an issue with the card tho.

**Comment by AndyLuz** [comment]
![Screenshot](https://user-images.githubusercontent.com/57171057/190192639-a239d4d2-eacd-4263-9296-715af4f6dbb7.jpg)

The same buttons and graph are working without a problem on other cards. 
I have noticed that if I add same light entity to the beginning, it works but the second light button still doesn't

And how do you align top icons to the right?


type: custom:room-card
title: Office
entity: switch.light_office
info_entities:
    entity: sensor.eye_office_air_temperature
    show_icon: 0
    state_color: true
    entity: sensor.eye_office_illuminance
    show_icon: 0
    state_color: true

**Comment by marcokreeft87** [comment]
There is not way to do that in the card. I advise card mod for this

**Comment by marcokreeft87** [comment]
Closed because of no response
