### ISSUE TITLE
Rows is not working

### ISSUE THREAD

**Issue by fightingmajor** [marcokreeft87/room-card#67]
I've formatted it a ton of different ways and can't get it to reproduce.  The example code in the wiki is missing the beginning of the info.  Each time I try to use Rows, when I start the second row, I get Configurtion Errors Detected : duplicate mapping Key.

<img width="980" alt="Screenshot 2022-09-27 at 12 37 02 AM" src="https://user-images.githubusercontent.com/17260650/192441048-42799d25-b262-4008-9c0e-28765feaea58.png">

**Comment by marcokreeft87** [comment]
You are missing the - in front of entities. Just like in the example of the wiki.

**Comment by fightingmajor** [comment]
So like this with the - in front of entries?
 
<img width="980" alt="Screenshot 2022-09-27 at 12 41 07 AM" src="https://user-images.githubusercontent.com/17260650/192441758-e51a1443-e451-456c-b19f-3d2487d9d03d.png">

**Comment by marcokreeft87** [comment]
Yes and probably lowercase R in rows

**Comment by fightingmajor** [comment]
> 

ya I fixed the r haha.  FYI, I was running 1.5.02 and it wasn't working still.  I grabbed 1.5.1 and then it does work now, but it messed up all of my others.  Which is the newest version?

**Comment by marcokreeft87** [comment]
v1.05.02 is the newest version. I switched up version notation
