### ISSUE TITLE
Allow more than 1 row of entities

### ISSUE THREAD

**Issue by mihsu81** [marcokreeft87/room-card#7]
Hi @marcokreeft87, 

Thanks a lot for this awesome card. Would be great if it would allow multiple rows of entities.

Or at least do you have a suggestion for which style to apply in order to split entities-row in multiple rows with a specific number of entities?

Thanks in advance.

**Comment by mihsu81** [comment]
I got it to split in multiple rows by using `flex-wrap: wrap`, but it would be better, in my opinion, to be able to do it directly from the card, without using additional styling.

```
style: |
  div.entities-row {
    justify-content: center;
    flex-wrap: wrap;
  }
```

**Comment by marcokreeft87** [comment]
Yeah it's styled flexible so my first idea would be keep adding entities. But it's a good idea for a feature to use your css. Thnx!

**Comment by mihsu81** [comment]
Cool. I'm glad I could help. 😊
