### ISSUE TITLE
Status updates are not propagated to items in section "cards:"

### ISSUE THREAD

**Issue by tomtom13** [marcokreeft87/room-card#75]
If one includes another card in subsection "cards:" - updates won't get propagated to it. Only way to see updated status (like light on / off or temp update) is to refresh whole page. 

As a simple example - inclusion of multiple-entity-row will not update any buttons.
```
cards:
  - entity: switch.office_main_power
    type: custom:multiple-entity-row
```

**Comment by marcokreeft87** [comment]
I will try that card tomorrow. I don't have that issue with other cards tho. Seems kind of weird to use that card inside room-card, but it should work

**Comment by marcokreeft87** [comment]
I have tried it. And it works perfectly fine. This is because the multiple-entity-row handles it own entities.

**Comment by tomtom13** [comment]
Here you go:

`type: custom:room-card
title: Office
info_entities:
  - entity: sensor.office_temp_sensor_1_temperature
    show_icon: false
    format: precision1
  - entity: sensor.office_temp_sensor_2_temperature
    show_icon: false
    format: precision1
  - entity: sensor.office_temp_sensor_3_temperature
    show_icon: false
    format: precision1
entities:
  - entity: light.office_main_light
    name: Ceiling
    show_icon: true
    state_color: true
    icon: mdi:ceiling-light-multiple
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - entity: light.office_desk_light
    name: Floor
    show_icon: true
    state_color: true
    icon: mdi:floor-lamp
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - entity: scene.office_main_white
    name: White
    show_icon: false
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.office_main_white
  - entity: scene.office_main_normal
    name: Normal
    show_icon: false
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.office_main_normal
  - entity: scene.office_main_relax
    name: Relax
    show_icon: false
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.office_main_relax
  - entity: scene.office_main_uv
    name: UV
    show_icon: false
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.office_main_uv
  - entity: scene.office_main_soho
    name: UV
    show_icon: false
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.office_main_soho
cards:
  - entity: switch.office_main_power
    type: custom:multiple-entity-row
    icon: mdi:lightning-bolt
    name: false
    tap_action:
      action: null
    hold_action:
      action: null
    show_state: false
    toggle: true
    state_color: false
    entities:
      - entity: switch.office_main_power
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
      - entity: switch.office_main_rig_power
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
      - entity: switch.office_printer
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
      - entity: switch.office_extraction_fan
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
      - entity: switch.office_test_equipment_1
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
      - entity: switch.comms_cabinet_server_power_1
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
      - entity: switch.comms_cabinet_server_power_2
        name: false
        icon: true
        tap_action:
          action: toggle
        state_color: true
  - entity: sensor.office_temp_sensor_1_humidity
    type: custom:multiple-entity-row
    name: Humidity
    tap_action:
      action: null
    hold_action:
      action: null
    show_state: false
    show_icon: false
    entities:
      - entity: sensor.office_temp_sensor_1_humidity
        name: '% 1'
        unit: false
        format: precision1
      - entity: sensor.office_temp_sensor_2_humidity
        name: '% 2'
        unit: false
        format: precision1
      - entity: sensor.office_temp_sensor_3_humidity
        name: '% 3'
        unit: false
        format: precision1
`

**Comment by marcokreeft87** [comment]
And which entities are not working?

**Comment by tomtom13** [comment]
Everything within section cards, works, but does not update. Tried on safari, firefox and HS app.

**Comment by marcokreeft87** [comment]
I think this problem lies with the multiple entities card. Sorry but I can't help you with this

**Comment by tomtom13** [comment]
Oki doki :)

**Comment by tomtom13** [comment]
Ok, so I did some more testing along with a good scotch, and I can say that your card does not propagate updates properly.

Here is an example for including a graph as a card:

```
type: custom:room-card
icon: mdi:car
title: Electricity
info_entities:
  - entity: sensor.master_electricity_meter_1_power
    format: precision1
entities:
  - entity: sensor.master_electricity_meter_1_energy
    show_icon: false
    name: Total consumed
    show_state: true
    format: precision0
cards:
  - type: custom:plotly-graph
    entities:
      - sensor.master_electricity_meter_1_power
    hours_to_show: 24
    refresh_interval: 10
```

**Comment by marcokreeft87** [comment]
It's working here and you are the first that is reporting this problem. I can't reproduce so I can't fix the issue for you. Maybe there is something else causing this? A Javascript error maybe?

**Comment by marcokreeft87** [comment]
Btw which scotch did you choose?
