### ISSUE TITLE
Allow for entities to show an actual value. 

### ISSUE THREAD

**Issue by tomtom13** [marcokreeft87/room-card#78]
I've personally not found a way to show a value instead of icon. I see example is using a glance, but glance is very limited and in it self doesn't allow removal of icons (icon can be set to nill, but still occupies space).

Being able to have an entity that shows a value would be nice.

**Comment by marcokreeft87** [comment]
Have you checked the wiki? This is possible as the card is now.

**Comment by tomtom13** [comment]
Yes as a card but cards can't be in the same row as entities, or at least I could not make it work due to lack working example .

**Comment by marcokreeft87** [comment]
I can't provide examples for every case. You have to do some tweaking yourself sometimes. Try using show_icon false.

**Comment by tomtom13** [comment]
OK @marcokreeft87, I found the culprit: show_state by default is false, while in docs it states that it's true. Forcing the value to true did fix the problem.

**Comment by marcokreeft87** [comment]
Ah good find! I will change the docs
