### ISSUE TITLE
Make state values slightly bigger. 

### ISSUE THREAD

**Issue by tomtom13** [marcokreeft87/room-card#79]
If one choses to not use an icon for a entity, but a state value - it's text is exactly the same as title. That doesn't look right. I would suggest making state value slightly larger (just slightly) and maybe making entity title text slightly darker, so it pronounces the value without distracting from it.

**Comment by marcokreeft87** [comment]
You can do that with the styles configuration.

**Comment by tomtom13** [comment]
@marcokreeft87 Seriously, I know that anybody can do anything with styles, but we're talking about "out of the box experience" .... most of people walk away if they have to faf about.

**Comment by marcokreeft87** [comment]
I can't make the card do anything anyone wants. The next person is gonna ask me to make it smaller for example. This way people can choose.
