### ISSUE TITLE
Values not refreshing on the Dashboard

### ISSUE THREAD

**Issue by elninosi** [marcokreeft87/room-card#80]
It looks like there is an issue with refreshing the values, for example I have provided luminosity

I've attached the picture of entity card and room-card. The values is refreshed on entity card but not on room-card.

![slika](https://user-images.githubusercontent.com/11082452/193661246-9f77b6ec-4c61-4246-b18f-6d32156ba601.png)

I'm also attaching the config of room-card:

```
type: custom:room-card
title: Living room
info_entities:
  - entity: binary_sensor.living_room_balcony_doors
    show_icon: true
    icon:
      state_on: mdi:window-open-variant
      state_off: mdi:window-closed-variant
  - entity: binary_sensor.living_room_sensor
    show_icon: true
    hide_if:
      entity: binary_sensor.living_room_sensor_unavailable
      state: true
  - entity: media_player.living_room_group
    icon: mdi:speaker-wireless
    show_icon: true
  - sensor.living_room_sensor_temperature
  - sensor.living_room_sensor_luminosity
cards:
  - type: custom:mini-media-player
    entity: media_player.living_room_group
    show_states:
      - playing
    group: true
    source: icon
    info: short
    hide:
      controls: true
card_mod:
  style: |
    ha-card {
      color: #EFEFEF;
      min-height:100%;
      border-radius: 15px;
    }
```

**Comment by marcokreeft87** [comment]
Do you have Javascript errors by any chance?

**Comment by elninosi** [comment]
None errors in Javascript console. I also thought that Card-mod might have performance issues (removed the custom styling) and it's still behaving the same.

**Comment by marcokreeft87** [comment]
Are the other entities refreshing? 
As I don't have this problem, at least not that I noticed, I will have to reproduce this. Hope to find some time tomorrow

**Comment by elninosi** [comment]
Both windows and motion sensor are working instantly.

**Comment by marcokreeft87** [comment]
Can you send me the attributes of the lumi sensor? I think it got something to do with the attributes

**Comment by elupus** [comment]
I also had refreshing issues when editing configuration in gui. Half of the time i had to save the edit dialog for changes to be visible in the gui. The example display in the edit dialog would update sporadically.

**Comment by elupus** [comment]
This might be one issue: https://github.com/marcokreeft87/room-card/blob/7b3d926325c107e55ee187051a4d1f065de65d14/src/index.ts#L54 doesnt that lock in the selected base entity. If base entity changes that wont execute. 

However does not look like its same issue as this issue.

**Comment by marcokreeft87** [comment]
How would you solve this? Because that line of code only checks if the main entity is given in the config. The logic of updating the card is in shouldUpdate(changedProps: PropertyValues): boolean

**Comment by elupus** [comment]
Any time a new hass or a new config is set, recalculate these values. If entity is missing set the values to none. It should not rely on default values.

Ps. I have very little frontend experience.

**Comment by marcokreeft87** [comment]
Yeah it kinda makes sense tho. Lets try it

**Comment by marcokreeft87** [comment]
@elninosi It looks like this is the fix. Can you test v1.06.13?

**Comment by elninosi** [comment]
Hi @marcokreeft87 unfortunately the issue is still there.
![slika](https://user-images.githubusercontent.com/11082452/194372135-0061e2dc-3774-4b5d-b1e7-ad942ece2e51.png)
Additional observation also the same is happening for temperature: 
![slika](https://user-images.githubusercontent.com/11082452/194372259-4ffe293c-795a-44ff-b28a-849fb20ecb48.png)

On the other hand icons for movement and door sensors are updated instantly.

**Comment by elupus** [comment]
Sounds like an real issue. Probably should not close the issue.

**Comment by marcokreeft87** [comment]
> Sounds like an real issue. Probably should not close the issue.

Well there is a workaround. I will try to fix it tomorrow

**Comment by marcokreeft87** [comment]
I found the bug I think. @elninosi  your latest info got me there :)

**Comment by marcokreeft87** [comment]
Check out v1.06.14 :)

**Comment by elninosi** [comment]
@marcokreeft87 I can confirm that new version solves the issue.

![slika](https://user-images.githubusercontent.com/11082452/194478783-78279f05-f7f5-4f36-877e-fba126436b6d.png)

Thank you.

**Comment by labaland** [comment]
i have to press f5 for stat to update.. many bugs here xD

**Comment by marcokreeft87** [comment]
> i have to press f5 for stat to update.. many bugs here xD

As you can see the bug was resolved. Would be nice to have some explanation of your issue. But please create a new issue because it's probably something different
