### ISSUE TITLE
Media player cards not always updating if inside cards: block

### ISSUE THREAD

**Issue by hugalafutro** [marcokreeft87/room-card#84]
**Describe the bug**
media-control or mini-media-player cards do not refresh inside cards: block. I am using Kodi if that is of any importance.

**To Reproduce**
1. Put either media-control or mini-media-player card inside a Room card's cards: block
2. Put the same card as standalone card right below
3. Start Kodi, play some media
4. Pause/Unpause the video on the Kodi device, and observe the cards. The standalone card will update immediately, the one inside cards: block shows playing until frontend reload or play/pause click, at which point it triggers play/pause and switches the icon even if it means displaying the wrong state icon. 
5. Stop the video on the Kodi device. The standalone card will clear immediately, the one inside cards: will not until Frontend reload

**Expected behavior**
Card should update immediately regardless if standalone or inside cards: block of Room card

**Screenshots**
I can make a video if you really need it, let me know.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser vivaldi (chrome based)
 - Version 5.5.2805.35

**Additional context**
nope

**Comment by marcokreeft87** [comment]
Are you sure they work correct outside the room card? Because I use them with plex and they always were behind in updating even before I made the room card

**Comment by hugalafutro** [comment]
For me they always updated instantly I noticed the lag (or the lack of update) when I moved it to Room card to get rid of the line between cards when using vertical stack.

I made a video, whatever you see happening on the bottom card happens the instant I do it on the Kodi keyboard (you can hear the clicks). As you can see inside the Room card only after reload.
https://www.youtube.com/watch?v=9tM7DZbS7JQ

**Comment by marcokreeft87** [comment]
You are right! Thanks for the video and info. I think I can fix this

**Comment by marcokreeft87** [comment]
Check out v1.06.21

**Comment by hugalafutro** [comment]
Good stuff, can confirm fixed in 1.06.21.

**Comment by marcokreeft87** [comment]
Thats something I cant fix

**Comment by hugalafutro** [comment]
No worries I'll learn to live with the divider line between cards in stack :)
