### ISSUE TITLE
Allow content_alignment per row, add justified alignement

### ISSUE THREAD

**Issue by hugalafutro** [marcokreeft87/room-card#88]
**Is your feature request related to a problem? Please describe.**
Just an enhancement to the recently released `content_alignment` option

**Have you tried if it is already a feature? Have you checked the wiki?**
Yes and I already like the center alignment a lot.

**Describe the solution you'd like**
I'd like to be able to define `content_alignment` per row (i.e. for each of the `- entities:`) instead per card.

I would love an "justified" option which would evenly spread all the entities across the whole length of card. So if it were 2 3 4 or 5 entities in a row, the 2 ones on the side would always be at the borders and the ones in between them would be evenly spaced. Hope that makes sense English ain't my 1st language.

**Describe alternatives you've considered**
I am perfectly fine with how the card is so far, you have been extremely quick with pushing the fixes and I don't wanna annoy you with requests. Just think it'd be cool to have this kind of customizability.

**Additional context**
Thank you for reading!

**Comment by marcokreeft87** [comment]
The justified option you can do with ```styles```.
The content_alignment per row, will go on the todo list

**Comment by marcokreeft87** [comment]
Check out version 1.06.40 :)

**Comment by hugalafutro** [comment]
I just got home, updated the card to 1.06.40, but I can't figure out where to put the `content_alignment` now. If I leave it in the main block where it was in 1.06.30 it does not apply.

If I have 3 rows of 3 entities like this:
```
rows:
  - entities:
      - entity:
      - entity:
      - entity:
  - entities:
      - entity:
      - entity:
      - entity:
  - entities:
      - entity:
      - entity:
      - entity:
```
where do I insert the `content_alignment` if I'd want the 1st row to left, 2nd to center and 3rd to right? I tried everywhich way but the border in HA editor just goes red and won't let me save the card.

**Comment by marcokreeft87** [comment]
Below the last entity. But it has to have the same indention as the dash

**Comment by hugalafutro** [comment]
Gotcha, I was trying the right indent but I was putting it at top.
